services:

  hotels:
    image: antogo8768/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - antogo-network
    
  rooms:
    image: antogo8768/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - antogo-network
    
  reservations:
    image: antogo8768/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - antogo-network
    
networks:
  antogo-network: